
wrap:
  service:
    enable: true #设置开关状态
    before: +++ #前缀
    after: ---- #后缀

#端口号
server:
  port: 8084



#服务名
spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: true

  redis:
    databse: 1
    host: localhost
    port: 6379
    password:
    timeouot: 1000s
    jedis:
      pool:
        max-active: 10
        max-wait: 5s
        max-idle: 10
        min-idle: 10


  # 数据源配置
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/dz_users?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
#    dirver-class-name: com.mysql.jdbc.Driver

#数据库配置
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.user.model

#注册的eureka服务地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  #自定义服务实例ID: 服务名+IP地址+端口号
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
