

#端口号
server:
  port: 8084

#服务名
spring:
  application:
    name: user-service
  # 数据源配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dz_users?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    dirver-class-name: com.mysql.jdbc.Driver

#数据库配置
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.user.model

#注册的eureka服务地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  #自定义服务实例ID: 服务名+IP地址+端口号
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}





