package com.user.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_job_mapping_1
 */
public class JobMapping {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_mapping_1.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   职位ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_mapping_1.job_id
     *
     * @mbg.generated
     */
    private Long jobId;

    /**
     * Database Column Remarks:
     *   品类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_mapping_1.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_mapping_1.passport_id
     *
     * @mbg.generated
     */
    private Long passportId;

    /**
     * Database Column Remarks:
     *   商家id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_mapping_1.worker_id
     *
     * @mbg.generated
     */
    private Long workerId;

    /**
     * Database Column Remarks:
     *   来源 1：预约；2：投递；
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_mapping_1.source
     *
     * @mbg.generated
     */
    private Byte source;

    /**
     * Database Column Remarks:
     *   映射状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_mapping_1.mapping_status
     *
     * @mbg.generated
     */
    private Integer mappingStatus;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_mapping_1.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_job_mapping_1.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_mapping_1.id
     *
     * @return the value of t_job_mapping_1.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_mapping_1.id
     *
     * @param id the value for t_job_mapping_1.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_mapping_1.job_id
     *
     * @return the value of t_job_mapping_1.job_id
     *
     * @mbg.generated
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_mapping_1.job_id
     *
     * @param jobId the value for t_job_mapping_1.job_id
     *
     * @mbg.generated
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_mapping_1.category_id
     *
     * @return the value of t_job_mapping_1.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_mapping_1.category_id
     *
     * @param categoryId the value for t_job_mapping_1.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_mapping_1.passport_id
     *
     * @return the value of t_job_mapping_1.passport_id
     *
     * @mbg.generated
     */
    public Long getPassportId() {
        return passportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_mapping_1.passport_id
     *
     * @param passportId the value for t_job_mapping_1.passport_id
     *
     * @mbg.generated
     */
    public void setPassportId(Long passportId) {
        this.passportId = passportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_mapping_1.worker_id
     *
     * @return the value of t_job_mapping_1.worker_id
     *
     * @mbg.generated
     */
    public Long getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_mapping_1.worker_id
     *
     * @param workerId the value for t_job_mapping_1.worker_id
     *
     * @mbg.generated
     */
    public void setWorkerId(Long workerId) {
        this.workerId = workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_mapping_1.source
     *
     * @return the value of t_job_mapping_1.source
     *
     * @mbg.generated
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_mapping_1.source
     *
     * @param source the value for t_job_mapping_1.source
     *
     * @mbg.generated
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_mapping_1.mapping_status
     *
     * @return the value of t_job_mapping_1.mapping_status
     *
     * @mbg.generated
     */
    public Integer getMappingStatus() {
        return mappingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_mapping_1.mapping_status
     *
     * @param mappingStatus the value for t_job_mapping_1.mapping_status
     *
     * @mbg.generated
     */
    public void setMappingStatus(Integer mappingStatus) {
        this.mappingStatus = mappingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_mapping_1.create_time
     *
     * @return the value of t_job_mapping_1.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_mapping_1.create_time
     *
     * @param createTime the value for t_job_mapping_1.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_job_mapping_1.update_time
     *
     * @return the value of t_job_mapping_1.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_job_mapping_1.update_time
     *
     * @param updateTime the value for t_job_mapping_1.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}